version: "3"
services:
  database:
    image: postgres:11
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
    expose:
      - "5432"
    networks:
      - internal
    volumes:
      - database_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    environment:
      SPRING_PROFILES_ACTIVE: "staging"
      DB_URL: "database:5432"
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: secretpassword
      TOKEN_SECRET_KEY: MjM0Njc4OTY3ODkyMzQ2Nzg5MjM0MjM0Njc4OTIzNDY3ODkyMzQyMzQyMzQyMzQyMzQyMzQyMzQyMzQyMzQ=
    expose:
      - "8080"
    networks:
      - internal
    depends_on:
      - database

  patient:
    build:
      context: ./frontend/patient
    expose:
      - "80"
    networks:
      - internal

  employee:
    build:
      context: ./frontend/employee
    expose:
      - "80"
    networks:
      - internal

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
    depends_on:
      - api
      - patient
      - employee

networks:
  internal:

volumes:
  database_data:
