spring.datasource:
  url: jdbc:postgresql://${DB_URL}/${DB_NAME}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto: update

app.security.tokenSecretKey: ${TOKEN_SECRET_KEY}
